//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.17 at 11:57:44 AM CET 
//


package load.hadoop.conf.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}parseconf"/>
 *         &lt;element ref="{}outconf"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parseconf",
    "outconf"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    protected Parseconf parseconf;
    @XmlElement(required = true)
    protected Outconf outconf;

    /**
     * Gets the value of the parseconf property.
     * 
     * @return
     *     possible object is
     *     {@link Parseconf }
     *     
     */
    public Parseconf getParseconf() {
        return parseconf;
    }

    /**
     * Sets the value of the parseconf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parseconf }
     *     
     */
    public void setParseconf(Parseconf value) {
        this.parseconf = value;
    }

    /**
     * Gets the value of the outconf property.
     * 
     * @return
     *     possible object is
     *     {@link Outconf }
     *     
     */
    public Outconf getOutconf() {
        return outconf;
    }

    /**
     * Sets the value of the outconf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outconf }
     *     
     */
    public void setOutconf(Outconf value) {
        this.outconf = value;
    }

}
