//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.16 at 05:40:33 PM CET 
//


package load.hadoop.conf.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the load.hadoop.conf.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Expression_QNAME = new QName("", "expression");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: load.hadoop.conf.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Subparses }
     * 
     */
    public Subparses createSubparses() {
        return new Subparses();
    }

    /**
     * Create an instance of {@link Parse }
     * 
     */
    public Parse createParse() {
        return new Parse();
    }

    /**
     * Create an instance of {@link Assemblies }
     * 
     */
    public Assemblies createAssemblies() {
        return new Assemblies();
    }

    /**
     * Create an instance of {@link Assembly }
     * 
     */
    public Assembly createAssembly() {
        return new Assembly();
    }

    /**
     * Create an instance of {@link Outconf }
     * 
     */
    public Outconf createOutconf() {
        return new Outconf();
    }

    /**
     * Create an instance of {@link Parseconf }
     * 
     */
    public Parseconf createParseconf() {
        return new Parseconf();
    }

    /**
     * Create an instance of {@link Constant }
     * 
     */
    public Constant createConstant() {
        return new Constant();
    }

    /**
     * Create an instance of {@link Constants }
     * 
     */
    public Constants createConstants() {
        return new Constants();
    }

    /**
     * Create an instance of {@link Filename }
     * 
     */
    public Filename createFilename() {
        return new Filename();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "expression")
    public JAXBElement<String> createExpression(String value) {
        return new JAXBElement<String>(_Expression_QNAME, String.class, null, value);
    }

}
